### ISSUE TITLE
The integration is not tolerant of temporary issues with the packet source.

### ISSUE THREAD

**Issue by brucemiranda** [ramses-rf/ramses_cc#181]
If **ramses_cc** detects an issue with the **HGI80**, it currently sets a Problem status, i.e. `binary_sensor.18_199952_status`

What might be even better is if it resets the serial interface and tries again when it detects an issue.

**Comment by zxdavb** [comment]
User reports: 
> A simple `Reload` of the integration seems to kick things back into life.

**Comment by zxdavb** [comment]
This is an automation to reload the integration if a problem is detected (thanks @brucemiranda):
```yaml
alias: Reload Ramses CC
description: Reload Ramses CC when HGI80 shows a Problem
trigger:
  - platform: state
    entity_id:
      - binary_sensor.18_002563_status
    to: "on"
condition: []
action:
  - service: homeassistant.reload_config_entry
    data:
      entry_id: 14f6287491ba233d7310fd7a82b32fec
mode: single
```
