### ISSUE TITLE
How to bind/fake a Nuaire CO2 Sensor

### ISSUE THREAD

**Issue by rjbungay** [ramses-rf/ramses_cc#196]
I have built a "RAMSES_ESP" device, installed Ramses_cc in HA and managed to fake and bind a 4-way switch to my Nuaire DRI-ECO-HEAT PIV which is all working OK.

I would now like to fake a CO2 sensor but the Wiki doesn't give instructions for this. I tried using a similar bind instruction as the 4-way switch on the off chance just replacing the device ID with the correct one but this didn't work (which I wasn't surprised by as I assume this is the code for the 4-way switch).

```
service: ramses_cc.bind_device
data:
  device_id: 32:602602
  offer:
    "22F1":
    "10E0":
  device_info: " I --- 32:602602 63:262142 --:------ 10E0 030 000001C85A01016CFFFFFFFFFFFF010607E0564D4E2D32334C4D48323300"
```

I have the following in my config flow schema:-
```
"18:024076":
  class: HGI
"30:096009":
  class: FAN
"32:123456":
  class: REM
  faked: true
  commands:
    normal: " I --- 32:123456 30:096009 --:------ 22F1 003 00020A"
    boost: " I --- 32:123456 30:096009 --:------ 22F1 003 00030A"
    heater_off: " I --- 32:123456 30:096009 --:------ 22F1 003 00090A"
    heater_auto: " I --- 32:123456 30:096009 --:------ 22F1 003 000A0A"
    battery_ok: " I --- 32:123456 --:------ 32:123456 1060 003 00FF01"
    get_fan_info: RQ --- 32:123456 30:096009 --:------ 31DA 001 00
"32:602602":
  class: CO2
  faked: true
```

What are the correct commands to bind the faked CO2 sensor to the Nuaire PIV?

I wish to do this as I understand from the manual that I will be able to boost the speed by 1 from the setpoint by sending a high CO2 reading whereas the "boost" command from the switch actually sets the unit to "purge" mode and sets the fan to full speed 6.

Any help getting this working would be appreciated.

As an aside, I seem to have had two devices appear in RAMSES while I was creating the setup and didn't have the whitelist enabled, HVC 32:031267 and HVC 32:078314. Is there a way to remove these from my system? So far I have found no way to delete them.
